setlocal showtabline=2
setlocal tabstop=4
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal comments=sO:\"\ -,mO:\"\ \ ,eO:\"\",f:\"
setlocal foldmethod=marker
setlocal keywordprg=:help
setlocal formatoptions-=o
setlocal formatoptions-=r
